apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-svc
spec:
  type: ClusterIP
  selector:
    app: {{.Values.name}}
  ports:
  - port: 80
    targetPort: {{int .Values.containerPort}}
    protocol: TCP
